# Generated by Django 5.2.4 on 2025-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javaquestion',
            name='correct_option',
            field=models.CharField(max_length=255),
        ),
    ]
