# Generated by Django 5.2.4 on 2025-07-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_javaquestion_correct_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='javaquestion',
            old_name='correct_option',
            new_name='correct_answer',
        ),
    ]
